export default [
    {
        id: 0,
        name: "Капуста",
        subName: "Белокачанная",
        category: "Овощи",
        brand: "УралМашСавхоз",
        country: "Россия",
        stock: 4,
        shift: {
            yaw: -120 * Math.PI / 180,
            pitch: 0.55,
        },
        size: {
            width: 100,
            height: 100,
        },
        cost: 34.16,
        costFloat: "1",
        measure: "кг",
        sizeItem: "1-4кг",
        src: "https://img3.zakaz.ua/upload.ec606ed0a25ddc6bce03f6749cf35159.1350x1350.jpg",
    },
    {
        id: 1,
        name: "Лейка для цветов",
        subName: "Синяя",
        category: "Хоз товары",
        brand: "TsjaoPunj",
        country: "Китай",
        stock: 8,
        shift: {
            yaw: 0,
            pitch: -2,
        },
        size: {
            width: 30,
            height: 30,
        },
        cost: 150,
        costFloat: "1",
        measure: "шт",
        sizeItem: "1.5л",
        src: "http://www.domosti.ru/images/product_store/460x460/55533.jpg",
    },
    {
        id: 2,
        name: "Кондиционер для белья",
        subName: "Фиалка",
        category: "Стиральная химия",
        brand: "Lenor",
        country: "Россия",
        stock: 10,
        shift: {
            yaw: 8 * Math.PI / 180,
            pitch: 0.78,
        },
        size: {
            width: 45,
            height: 45,
        },
        cost: 84.50,
        costFloat: "1",
        measure: "шт",
        sizeItem: "0,75л",
        src: "https://azcdn.pioneer.pgsitecore.com/en-gb/-/media/Downy_UK/Images/DT/Products/Products_UK/LenorSpringAwakening44_640x640.png?w=460&v=1-201708041137",
    },
    {
        id: 3,
        name: "Масло подсолнечное",
        subName: "Рафинированное нефильтрованное",
        category: "Продукты",
        brand: "Злато",
        country: "Россия",
        stock: 30,
        shift: {
            yaw: 110 * Math.PI / 180,
            pitch: 0.53,
        },
        size: {
            width: 80,
            height: 80,
        },
        cost: 64.90,
        costFloat: "1",
        measure: "шт",
        sizeItem: "1л",
        src: "https://av.ru/product/hd1/hdd/8843286970398.jpg",
    },
];