export default [
    {
        id: 0,
        name: 'Капуста',
        subName: 'Белокачанная',
        category: 'Овощи',
        brand: 'УралМашСавхоз',
        country: 'Россия',
        stock: 4,
        shift: {
            yaw: -123,
            pitch: -35,
        },
        size: {
            width: 40,
            height: 40,
        },
        cost: 34.16,
        costFloat: '1',
        measure: 'кг',
        sizeItem: '1-4кг',
        src: 'https://img3.zakaz.ua/upload.ec606ed0a25ddc6bce03f6749cf35159.1350x1350.jpg',
    },
    {
        id: 1,
        name: 'Лейка для цветов',
        subName: 'Синяя',
        category: 'Хоз товары',
        brand: 'TsjaoPunj',
        country: 'Китай',
        stock: 8,
        shift: {
            yaw: -3,
            pitch: -4,
        },
        size: {
            width: 15,
            height: 15,
        },
        cost: 150,
        costFloat: '1',
        measure: 'шт',
        sizeItem: '1.5л',
        src: 'http://www.domosti.ru/images/product_store/460x460/55533.jpg',
    },
    {
        id: 2,
        name: 'Кондиционер для белья',
        subName: 'Фиалка',
        category: 'Стиральная химия',
        brand: 'Lenor',
        country: 'Россия',
        stock: 10,
        shift: {
            yaw: 10,
            pitch: -50,
        },
        size: {
            width: 35,
            height: 35,
        },
        cost: 84.50,
        costFloat: '1',
        measure: 'шт',
        sizeItem: '0,75л',
        src: 'https://azcdn.pioneer.pgsitecore.com/en-gb/-/media/Downy_UK/Images/DT/Products/Products_UK/LenorSpringAwakening44_640x640.png?w=460&v=1-201708041137',
    },
    {
        id: 3,
        name: 'Масло подсолнечное',
        subName: 'Рафинированное нефильтрованное',
        category: 'Продукты',
        brand: 'Злато',
        country: 'Россия',
        stock: 30,
        shift: {
            yaw: 113,
            pitch: -30,
        },
        size: {
            width: 50,
            height: 50,
        },
        cost: 64.90,
        costFloat: '1',
        measure: 'шт',
        sizeItem: '1л',
        src: 'https://av.ru/product/hd1/hdd/8843286970398.jpg',
    },
];
